# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Orankey'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["orankey_left","orankey_right"]'
      clipboard: '["mac"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000"]'
      branches: '["zmkfirmware/zmk/main"]'
